### ISSUE TITLE
Import Rewriter does not rewrite paths if hash (or any other name except `/[name].js`) is used in the entryFileNames

### ISSUE THREAD

**Issue by l3szek** [aem-vite/import-rewriter#2]
### Describe the bug

Import Rewriter does not rewrite paths if `hash` (or any other name except `/[name].js`) is used in the `entryFileNames` in `rollupOptions` `output`. 

### Reproduction

In rollupOptions, specify the `hash` to be added to the `entryFileNames`: 

```
rollupOptions: {
      output: {
        assetFileNames: 'clientlib-site/resources/[ext]/[name][extname]',
        chunkFileNames: 'clientlib-site/resources/chunks/[name].[hash].js',
        entryFileNames: 'clientlib-site/resources/js/[name].[hash].js',
      },
    },
```
This will cause the relative paths to the `bundle.{hash}.js` be used in the bundle.js and chunks js files, instead of the absolute paths to the clientlibs specified in the **bundlesImportRewriter** `publicPath`

### System Info

Output of `npx envinfo --system --npmPackages @aem-vite/aem-vite --binaries --browsers`:

```node
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 10.83 GB / 30.95 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /snap/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 20230430.125247.0 - /usr/local/bin/watchman
```

Used package manager: npm

**Comment by cshawaus** [comment]
Hi @l3szek,

Apologies for the delay in replying. Would you be able to provide your Rollup `input` configuration?

The `output` configuration has no impact on the outcome of bundle paths as this is completed well before `import-rewriter` executes.
